In [3]:
import pandas as pd
import os
import numpy as np
import nltk
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer, PorterStemmer
import re

In [5]:
df = pd.read_csv("C:/Users/yunus/Desktop/Bahar Dersleri/Yapay Zeka Proje/arac-arizadeseni-eslestirme/data/raw/all_data.csv")

In [7]:
df.head()

,pdate,pdate 2,marka,cheader,cheader 2,comments
0,Jul 20,2017,Fiesta,Transmission Failed,"39,234 miles","Since 2011, there have been numerous issues. T..."
1,Mar 18,2017,Fiesta,Transmission Failed,"50,013 miles","I have had this car for just over a year, but ..."
2,Jan 06,2017,Fiesta,Transmission Failed,"37,000 miles",I will NEVER be purchasing a Ford vehicle or i...
3,Oct 20,2016,Fiesta,Transmission Failed,"106,000 miles",I was reading a comment posted by another 2011...
4,Mar 14,2015,Fiesta SE 4 cyl,Transmission Failed,"42,000 miles",We bought this Fiesta in February 2015. We hav...

In [9]:
def preprocess_text(text):
    sentences = nltk.sent_tokenize(text)
    processed_sentences = []
    for sentence in sentences:
        # 2. Küçük harfe çevirme
        sentence = sentence.lower()
        
        # 3. Noktalama işaretlerini kaldırma
        sentence = re.sub(r'[^\w\s]', '', sentence)
        
        # 4. Tokenizasyon
        tokens = nltk.word_tokenize(sentence)
        
        # 5. Stop word temizliği
        stop_words = set(stopwords.words('turkish'))
        tokens = [token for token in tokens if token not in stop_words]
        
        # 6. Lemmatizasyon
        lemmatizer = WordNetLemmatizer()
        tokens = [lemmatizer.lemmatize(token) for token in tokens]
        
        processed_sentences.append(tokens)
    
    return processed_sentences

In [11]:
# Fonksiyonu kullanarak işlemleri uygulama
df['comments_processed'] = df['comments'].apply(preprocess_text)

In [25]:
print(df['comments_processed'].head())

0    [[since, 2011, there, have, been, numerous, is...
1    [[i, have, had, this, car, for, just, over, a,...
2    [[i, will, never, be, purchasing, a, ford, veh...
3    [[i, wa, reading, a, comment, posted, by, anot...
4    [[we, bought, this, fiesta, in, february, 2015...
Name: comments_processed, dtype: object

In [27]:
df.to_csv("C:/Users/yunus/Desktop/Bahar Dersleri/Yapay Zeka Proje/arac-arizadeseni-eslestirme/data/raw/preprocessed_data_lemmatized_only.csv", index=False)

In [29]:
veri = pd.read_csv("C:/Users/yunus/Desktop/Bahar Dersleri/Yapay Zeka Proje/arac-arizadeseni-eslestirme/data/raw/preprocessed_data_lemmatized_only.csv")
veri.head(10)

,pdate,pdate 2,marka,cheader,cheader 2,comments,comments_processed
0,Jul 20,2017,Fiesta,Transmission Failed,"39,234 miles","Since 2011, there have been numerous issues. T...","[['since', '2011', 'there', 'have', 'been', 'n..."
1,Mar 18,2017,Fiesta,Transmission Failed,"50,013 miles","I have had this car for just over a year, but ...","[['i', 'have', 'had', 'this', 'car', 'for', 'j..."
2,Jan 06,2017,Fiesta,Transmission Failed,"37,000 miles",I will NEVER be purchasing a Ford vehicle or i...,"[['i', 'will', 'never', 'be', 'purchasing', 'a..."
3,Oct 20,2016,Fiesta,Transmission Failed,"106,000 miles",I was reading a comment posted by another 2011...,"[['i', 'wa', 'reading', 'a', 'comment', 'poste..."
4,Mar 14,2015,Fiesta SE 4 cyl,Transmission Failed,"42,000 miles",We bought this Fiesta in February 2015. We hav...,"[['we', 'bought', 'this', 'fiesta', 'in', 'feb..."
5,Nov 05,2016,Fiesta SES,Transmission Failed,"100,000 miles","After having the car for two years, the car ju...","[['after', 'having', 'the', 'car', 'for', 'two..."
6,Dec 26,2013,Fiesta,Transmission Failed,"114,905 miles",This was a huge safety concern especially on t...,"[['this', 'wa', 'a', 'huge', 'safety', 'concer..."
7,Aug 15,2012,Fiesta SE 4,Transmission Failed,"5,672 miles","In Winnipeg, entering off ramp, driving too cl...","[['in', 'winnipeg', 'entering', 'off', 'ramp',..."
8,Jan 08,2016,Fiesta SE 4,Transmission Failed,"127,047 miles","I purchased this car in good faith from Ford, ...","[['i', 'purchased', 'this', 'car', 'in', 'good..."
9,Nov 29,2015,Fiesta SE 4,Transmission Failed,"61,400 miles",We purchased a 2011 Ford Fiesta in October 201...,"[['we', 'purchased', 'a', '2011', 'ford', 'fie..."

In [31]:
df2 = pd.read_csv("C:/Users/yunus/Desktop/Bahar Dersleri/Yapay Zeka Proje/arac-arizadeseni-eslestirme/data/raw/all_data.csv")

In [33]:
def stem_text(text):
  #Cümlelere ayırma
    sentences = nltk.sent_tokenize(text)
    
    processed_sentences = []
    for sentence in sentences:
        #Küçük harfe çevirme
        sentence = sentence.lower()
        #Noktalama işaretlerini kaldırma
        sentence = re.sub(r'[^\w\s]', '', sentence)
        #Tokenizasyon
        tokens = nltk.word_tokenize(sentence)
        #Stop word temizleme
        stop_words = set(stopwords.words('english'))
        tokens = [token for token in tokens if token not in stop_words]
        #Stemming
        stemmer = PorterStemmer()
        tokens = [stemmer.stem(token) for token in tokens]
        processed_sentences.append(tokens)
    return processed_sentences

In [35]:
df2['comments_stemmed'] = df2['comments'].apply(stem_text)

In [37]:
df2.to_csv("C:/Users/yunus/Desktop/Bahar Dersleri/Yapay Zeka Proje/arac-arizadeseni-eslestirme/data/raw/preprocessed_data_stemmed_only.csv",index=False)

In [39]:
veri2 = pd.read_csv("C:/Users/yunus/Desktop/Bahar Dersleri/Yapay Zeka Proje/arac-arizadeseni-eslestirme/data/processed/preprocessed_data_stemmed_only.csv")

In [41]:
veri2.head()

,pdate,pdate 2,marka,cheader,cheader 2,comments,comments_stemmed
0,Jul 20,2017,Fiesta,Transmission Failed,"39,234 miles","Since 2011, there have been numerous issues. T...","['sinc', '2011', 'numer', 'issu', 'vehicl', 'r..."
1,Mar 18,2017,Fiesta,Transmission Failed,"50,013 miles","I have had this car for just over a year, but ...","['car', 'year', 'driven', '21', 'day', 'car', ..."
2,Jan 06,2017,Fiesta,Transmission Failed,"37,000 miles",I will NEVER be purchasing a Ford vehicle or i...,"['never', 'purchas', 'ford', 'vehicl', 'item',..."
3,Oct 20,2016,Fiesta,Transmission Failed,"106,000 miles",I was reading a comment posted by another 2011...,"['read', 'comment', 'post', 'anoth', '2011', '..."
4,Mar 14,2015,Fiesta SE 4 cyl,Transmission Failed,"42,000 miles",We bought this Fiesta in February 2015. We hav...,"['bought', 'fiesta', 'februari', '2015', 'mani..."